Docs: Add rustc as dependency for source installation
When building Home Assistant and its required dependencies from source (e.g. on a platform without pre-built wheels),
a recent version of the Rust compiler is required to build the Python "cryptography" module.

Otherwise, the following error occurs:
>  running build_rust  
>  error: can't find Rust compiler